steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - '-c'
      - >
        ls -al

        echo "Cleaning up VM before deployment" &&

        gcloud compute ssh insa-prod-mgmt-vm --zone=asia-south1-c
        --tunnel-through-iap --quiet --command="


        if [ -d \"${_APP_DIR}/io-tmp\" ]; then
          rm -rf \"${_APP_DIR}/io-tmp\"
          echo \"Removed existing io-tmp directory\"
        fi &&

        mkdir -p \"${_APP_DIR}/io-tmp\" &&

        echo \"Created fresh io-tmp directory\""

        echo \"Starting file transfer\" &&


        gcloud compute scp --recurse ./ insa-prod-mgmt-vm:$_APP_DIR/io-tmp/
        --zone=asia-south1-c --tunnel-through-iap --project=insa-prod &&

        gcloud compute ssh insa-prod-mgmt-vm --zone=asia-south1-c
        --tunnel-through-iap --quiet --command="

        export APP_DIR=\"${_APP_DIR}\" && \

        cp  -r ./  $_APP_DIR/io-tmp/ && ls -al $_APP_DIR/io-tmp/ && \

        echo \"Creating deployment scripts\" && \

        mkdir -p scripts && \

        whoami && \

        echo \"APP_DIR: ${_APP_DIR}\" &&  \ 

        cat > scripts/script.sh << 'SCRIPT_EOF'

        #!/bin/bash


        cd \"$_APP_DIR\"


        if [ -d \"io-tmp\" ]; then
            sudo chown -R ubuntu:ubuntu io-tmp
        else
            echo \"Error: Directory io-tmp does not exist.\"
            exit 1
        fi


        mkdir -pv io


        if [ -d \"io-tmp/io\" ]; then
            echo \"Dry run to remove io folder contents\"
            rm -rf io/*
            echo \"Dry run to move from io-tmp/io to io folder\"
            mv -f io-tmp/io/* io/
            ls -ltr io/
        else
            echo \"Error: Directory io-tmp/io does not exist.\"
            exit 1
        fi


        if [ -d \"io-tmp\" ]; then
            echo \"Dry run to remove io-tmp folder contents\"
            rm -rf io-tmp
        fi


        echo \"Script executed successfully.\"

        SCRIPT_EOF

        chmod +x scripts/script.sh && \

        ./scripts/script.sh"
    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: projects/insa-prod/locations/asia-south1/workerPools/insa-prod-worker-pool
substitutions:
  _APP_DIR: /home/ubuntu/insa-engine/efs-data/insa-storage/kyp-prod/insa-io/
